// PANTALLA DE LOS REPORTES
// TODO SE HARA EN BASE AL ADMINISTRADOR

// PARA PODER OCULTAR ELEMENTOS, COMPONENTES, FUNCIONALIDADES:
// HAREMOS EL USO DE CONTEXTOS PARA QUE DEPENDIENDO QUIEN INICIE SESION, SE MUESTREN SUS COMPONENTES
// ASI EVITAMOS EL DUPLICADO DE CODIGO INNECESARIO (OSEA TENER DOS INTERFACES)